# Generated by Django 4.0.4 on 2022-05-06 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shiftbid', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shfitbid',
            new_name='Shiftbid',
        ),
        migrations.CreateModel(
            name='Seniority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seniority_number', models.PositiveIntegerField()),
                ('agent_name', models.CharField(max_length=50)),
                ('agent_email', models.EmailField(max_length=254)),
                ('shiftbid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftbid.shiftbid')),
            ],
        ),
    ]
