# Generated by Django 4.0.4 on 2022-05-06 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shiftbid', '0002_rename_shfitbid_shiftbid_seniority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_description', models.CharField(max_length=100)),
                ('agent_email', models.EmailField(max_length=254, null=True)),
                ('shiftbid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftbid.shiftbid')),
            ],
        ),
    ]
