# Generated by Django 4.0.4 on 2022-05-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftbid', '0003_shift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftbid',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='seniority',
            name='seniority_status',
            field=models.CharField(choices=[('c', 'created'), ('s', 'sent'), ('f', 'finished')], default='c', max_length=1),
        ),
    ]
